version: '3.11'

networks:
  custom:
    name: alluxio-network
    external: true

volumes:
  share:
    name: alluxio-share
    external: true
  keystore:
    driver: local

services:
  kdc:
    extends:
      file: ../../component/kerberos.yml
      service: kdc
  namenode:
    extends:
      file: ../../component/hadoop.yml
      service: namenode
    environment:
      - DOMAIN=${DOMAIN}
      - REALM=${REALM}
      - KERB_ADMIN_USER=${KERB_ADMIN_USER}
      - KERB_ADMIN_PASS=${KERB_ADMIN_PASS}
      - KERB_USER_PASS=${KERB_USER_PASS}
    volumes:
      - keystore:/etc/ssl/certs
  datanode:
    extends:
      file: ../../component/hadoop.yml
      service: datanode
    environment:
      - DOMAIN=${DOMAIN}
      - REALM=${REALM}
      - KERB_ADMIN_USER=${KERB_ADMIN_USER}
      - KERB_ADMIN_PASS=${KERB_ADMIN_PASS}
      - KERB_USER_PASS=${KERB_USER_PASS}
    volumes:
      - keystore:/etc/ssl/certs