version: '3.11'

networks:
  custom:
    name: alluxio-network
    external: true

volumes:
  share:
    name: alluxio-share
    external: true

services:
  kdc:
    extends:
      file: ../../docker-compose/kerberos.yml
      service: kdc
  namenode:
    extends:
      file: ../../docker-compose/hadoop.yml
      service: namenode
  datanode:
    extends:
      file: ../../docker-compose/hadoop.yml
      service: datanode