version: '3.11'

networks:
  custom:
    name: alluxio-network
    external: true

volumes:
  share:
    name: alluxio-share
    external: true

services:
  kdc:
    extends:
      file: ../../component/kerberos.yml
      service: kdc
  namenode:
    extends:
      file: ../../component/hadoop.yml
      service: namenode
    networks:
      custom:
        ipv4_address: 172.22.0.2
    extra_hosts:
      - "datanode.${DOMAIN}: 172.22.0.3"
    environment:
      - DOMAIN=${DOMAIN}
      - REALM=${REALM}
      - KERB_ADMIN_USER=${KERB_ADMIN_USER}
      - KERB_ADMIN_PASS=${KERB_ADMIN_PASS}
      - KERB_USER_PASS=${KERB_USER_PASS}
  datanode:
    extends:
      file: ../../component/hadoop.yml
      service: datanode
    networks:
      custom:
        ipv4_address: 172.22.0.3
    extra_hosts:
      - "namenode.${DOMAIN}: 172.22.0.2"
    environment:
      - DOMAIN=${DOMAIN}
      - REALM=${REALM}
      - KERB_ADMIN_USER=${KERB_ADMIN_USER}
      - KERB_ADMIN_PASS=${KERB_ADMIN_PASS}
      - KERB_USER_PASS=${KERB_USER_PASS}