version: '3.11'

networks:
  custom:
    name: alluxio-network
    external: true

volumes:
  share:
    name: alluxio-share
    external: true

services:
  namenode:
    image: apache/hadoop:3
    networks:
      custom:
    hostname: namenode.${DOMAIN}
    environment:
      - NAMENODE_FQDN=namenode.${DOMAIN}
    volumes:
      - ../../entrypoint:/tmp/entrypoint
      - ../../config:/tmp/config
      - share:/share
    entrypoint: /tmp/entrypoint/hadoop/entrypoint.sh
    
  datanode:
    extends:
      service: namenode
    hostname: datanode.${DOMAIN}

