version: '3.11'

services:
  kdc:
    extends:
      file: ../../docker-compose/kerberos.yml
      service: kdc
  namenode:
    extends:
      file: ../../docker-compose/hadoop.yml
      service: namednode
  datanode:
    extends:
      file: ../../docker-compose/hadoop.yml
      service: datanode