version: '3.11'

services:
  namenode:
    image: apache/hadoop:3
    networks:
      custom:
    hostname: namenode.${DOMAIN}
    container_name: namenode.${DOMAIN}
    environment:
      - NAMENODE_FQDN=namenode.${DOMAIN}
      - INTEGRATION_TMP_DIR=/integration/tmp
    volumes:
      - ../config:/config
      - ../entrypoint:/entrypoint
      - ../integration:/integration
      - share:/share
    entrypoint: /entrypoint/hadoop/entrypoint.sh
    
  datanode:
    extends:
      service: namenode
    hostname: datanode.${DOMAIN}
    container_name: datanode.${DOMAIN}

