version: '3.11'

services:
  hms:
    image: alluxio-playground-docker/hive:3.1.3
    networks:
      custom:
    hostname: hms.alluxio.io
    environment:
      - INTEGRATION_TMP_DIR=/integration/tmp
    volumes:
      - ../config:/config
      - ../entrypoint:/entrypoint
      - ../integration:/integration
    entrypoint: /entrypoint/hivemetastore/entrypoint.sh
    expose:
      - 9083