version: "3.11"

services:
  statestored:
    image: apache/impala:4.0.0-statestored
    networks:
      custom:
    ports:
      - "25010:25010" # Web debug UI
    hostname: impala-statestored.alluxio.io
    environment:
      - INTEGRATION_TMP_DIR=/integration/tmp
    volumes:
      - ../config:/config
      - ../entrypoint:/entrypoint
      - ../integration:/integration
    entrypoint: /entrypoint/impala/entrypoint.sh
  catalogd:
    extends:
      service: statestored
    depends_on:
      - statestored
    image: apache/impala:4.0.0-catalogd
    ports:
      - "25020:25020" # Web debug UI
    hostname: impala-catalogd.alluxio.io
  impalad:
    extends:
      service: statestored
    image: apache/impala:4.0.0-impalad_coord_exec
    depends_on:
      - statestored
      - catalogd
    ports:
      - "21050:21050" # HS2 endpoint
      - "25000:25000" # Web debug UI
      - "28000:28000" # HS2 over HTTP endpoint.
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx1g" # Keep the Java heap small to preserve memory for query execution.
      - INTEGRATION_TMP_DIR=/integration/tmp