version: '3.11'

services:
  kdc:
    image: sequenceiq/kerberos
    networks:
      custom:
    hostname: kdc.${DOMAIN}
    volumes:
      - /dev/urandom:/dev/random
      - /etc/localtime:/etc/localtime:ro
      - ../config:/config
      - ../entrypoint:/entrypoint
      - ../integration:/integration
    environment:
      - DOMAIN=${DOMAIN}
      - REALM=${REALM}
      - DOMAIN_REALM=${DOMAIN}
      - KERB_MASTER_KEY=masterkey
      - KERB_ADMIN_USE=admin
      - KERB_ADMIN_PASS=admin
      - INTEGRATION_TMP_DIR=/integration/tmp
    entrypoint: /entrypoint/kerberos/entrypoint.sh