version: '3.11'

services:
  kdc:
    image: sequenceiq/kerberos
    networks:
      custom:
    hostname: kdc.${DOMAIN}
    volumes:
      - ../entrypoint:/tmp/entrypoint
      - ../config:/tmp/config
      - /dev/urandom:/dev/random
      - /etc/localtime:/etc/localtime:ro
      - share:/share
    environment:
      - REALM=${REALM}
      - DOMAIN_REALM=${DOMAIN}
      - KERB_MASTER_KEY=masterkey
      - KERB_ADMIN_USE=admin
      - KERB_ADMIN_PASS=admin
    entrypoint: /tmp/entrypoint/kerberos/entrypoint.sh