version: '3.11'

services:
  presto:
    image: ahanaio/prestodb-sandbox:0.278
    networks:
      custom:
    hostname: presto.${DOMAIN}
    volumes:
      - ../config:/config
      - ../entrypoint:/entrypoint
      - share:/share
    environment:
      - DOMAIN=${DOMAIN}