version: '3.11'

services:
  presto:
    image: ahanaio/prestodb-sandbox:0.278
    networks:
      custom:
    hostname: presto.alluxio.io
    environment:
      - INTEGRATION_TMP_DIR=/integration/tmp
    volumes:
      - ../config:/config
      - ../entrypoint:/entrypoint
      - ../integration:/integration
    entrypoint: /entrypoint/presto/entrypoint.sh